# Linter workflow

name: Linter

on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v5.1.1
        env:
          # Only lints new/edited files
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_GOOGLE_JAVA_FORMAT: false
          VALIDATE_JSCPD: false
          VALIDATE_MARKDOWN: false
          JAVA_FILE_NAME: 'checkstyle.xml'